/*****************************************************************************************************
Fecha : 05/10/2016
----------------------------------------------------------------------------------------------------
 Detalle :
     Modelo de ListaMaterialesProduccion
-------------------------------------------------------------------------------------------------
Fecha       |   Desarrollador   	|   Modificación
-------------------------------------------------------------------------------------------------
05/10/2016  |   Alejandro Saa G		|   Inicio de Configuración
*****************************************************************************************************/
ListaMaterialesProduccion:
LOAD AP_QST_MASTERPRODORDID,
     ITEMID,
     AP_QST_ITEMNAME,
     COSTGROUPID,
     INVENTDIMID,
     UNITID,
     PRODLINETYPE,
     BOMQTY,
     VENDID
FROM
[..\QVD\ListaMaterialesProduccion.QVD]
(qvd);
