/*----------------------------------------------------------------------------------------------------
 Detalle :
    Modelo de Dimensiones: CIF
-------------------------------------------------------------------------------------------------
Fecha       |   Desarrollador   |   Modificación
-------------------------------------------------------------------------------------------------
10/12/2016  |   malemos         |   Inicio de Configuración
*****************************************************************************************************/
CIF:
	LOAD
		date(floor(ACCOUNTINGDATE))						as SK.FECHA, 
		Date(ACCOUNTINGDATE,'DD/MM/YYYY')				as CIF.Fecha,				
		CUENTA_N2 										as CIF.IdCuentaN2, 
		NOMBRE_CUENTA_N2								as CIF.CuentaN2, 
		DEBITO+CREDITO 									as CIF.Neto
	FROM
	[..\QVD\QST_Modelledgertrans.QVD]
	(qvd)
	Where CUENTA_N2=73;