/*
Fecha : 20/09/2016
----------------------------------------------------------------------------------------------------
 Detalle :
	Creación del Modelo: Maestro de Insumos.
-------------------------------------------------------------------------------------------------
Fecha       |   Desarrollador     |   Modificación
-------------------------------------------------------------------------------------------------
06/10/2016  |   Alejandro Saa G.  |   Inicio de Configuración
*****************************************************************************************************/
Insumo:
	LOAD
		ITEMID          as SK.Insumo,
		ITEMID          as Insumo.IdInsumo, 
		AP_QST_ITEMNAME as Insumo.NombreInsumo,
		NAMEALIAS       as Insumo.AliasInsumo,
		BOMUNITID       as Insumo.UnidadInsumo,
		COSTGROUPID     as Insumo.IdGrupoCosto,
		NAME            as Insumo.NombreGrupoCosto
	FROM
	[..\QVD\MaestroInsumos.QVD]
	(qvd);
