/*----------------------------------------------------------------------------------------------------
 Detalle :
    Extracción de Dimensiones: Logistica
-------------------------------------------------------------------------------------------------
Fecha       |   Desarrollador    |   Modificación
-------------------------------------------------------------------------------------------------
09/11/2016  |   Alejandro Saa G  |   Inicio de Configuración
*****************************************************************************************************/
EntradaProducto:
  SQL SELECT 
    CODDIARIO,
    TIPOTRANSF,
    FECHATRANSF,
    CODLOCALIDAD,
    CODARTICULO,
    COLORID,
    TALLA,
    CANTTRANSFE,
    CODORDENPROD
  FROM QST_MODELENTRADAPRODUCTO;

STORE EntradaProducto INTO [..\QVD\QST_ModelEntradaProducto.QVD](qvd);
DROP TABLE EntradaProducto;
