/*
Fecha : 09/11/2016
----------------------------------------------------------------------------------------------------
 Detalle :
	Creación del Modelo: Maestro de Localidades.
-------------------------------------------------------------------------------------------------
Fecha       |   Desarrollador     |   Modificación
-------------------------------------------------------------------------------------------------
09/11/2016  |   Alejandro Saa G.  |   Inicio de Configuración
*****************************************************************************************************/
MaestroLocalidades:
LOAD 
	SK.LOCALIDAD, 
	Localidad.Id, 
	Localidad.Nombre
FROM
[$(vRutaTra)_Localidad.QVD]
(qvd);