/*----------------------------------------------------------------------------------------------------
	Detalle :
	Extracción de Hechos: Extracción de lista de materiales para 
	-------------------------------------------------------------------------------------------------
	Fecha       |   Desarrollador   |   Modificación
	-------------------------------------------------------------------------------------------------
	11/04/2016  |   malemos         |   Inicio de Configuración
*****************************************************************************************************/

ListaMateriales_QV:
	SQL Select 
		CodigoBom,
		Substring(CodigoBom,38,46) as AprobacionDiseño,
		CodigoProducto,
		CodigoMaterial,
		AprobadoPor,
		CantidadComun,
		UnidadMedidaMaterial,
		FechaCreacion
	From ListaMateriales_QV;

STORE ListaMateriales_QV INTO [..\QVD\PLM\ListaMateriales_QV.QVD](qvd);
DROP TABLE ListaMateriales_QV;	