/*----------------------------------------------------------------------------------------------------
 Detalle :
    Extracción de Dimensiones: Productos PLM
-------------------------------------------------------------------------------------------------
Fecha       |   Desarrollador   |   Modificación
-------------------------------------------------------------------------------------------------
10/18/2016  |   malemos         |   Inicio de Configuración
*****************************************************************************************************/

Product_PLM:
	SQL SELECT 
		"_id_",
		Code,
		ParentSeason,
		Collection,
		"QST_StyleAttr_Genero_enum",
		"QST_StyleAttr_Linea_enum",
		"QST_StyleAttr_Marca_enum",
		"QST_StyleAttr_sublinea_enum",
		"Node Name",
		Category1,
		Category2,
		"QST_StyleAttr_BandaPrecio_enum",
		"QST_StyleAttr_CodigoDisenador_enum",
		"QST_StyleAttr_Empresa_enum",
		"QST_StyleAttr_NivelModa_enum",
		"QST_StyleAttr_SemanaEntrada_enum",
		"QST_StyleAttr_TipoAdquisicion_enum",
		"QST_StyleAttr_TamanoLoteAprobado_enum",
		"QST_StyleAttr_TamanoLotePropuesto_enum",
		"QST_StyleAttr_TipoPrenda_enum",
		"QST_StyleAttr_TipoProducto_enum",
		"QST_StyleAttr_GrupoProductos_enum",
		"QST_StyleAttr_Cuello_enum",
		"QST_StyleAttr_Manga_enum",
		"QST_StyleAttr_Silueta_enum",
		"QST_StyleAttr_EstadoAprobacion_enum",
		"QST_StyleAttr_AprobComite_enum",
		"QST_AparienciaDetalladaStyle_enum",
		"QST_AparienciaGeneral_enum",
		"QST_tipologiatejido_enum",
		"QST_Style_StatusBOM_enum",
		"QST_Style_StatusBOM_string",
		ProductType,
		"___CT",
		"___CR",
		"QST_Style_Descripcion_string",
		"QST_StyleAttr_SisproCode_string",
		Theme,
		"QST_Style_AsigPatronista_boolean",
		"QST_StyleAttr_PaisDeOrigen_enum",
		"QST_StyleAttr_CodigoPatronista_enum",
		"QST_StyleAttr_Lavado_enum",
		"QST_StyleAttr_hilos_strig",
		"QST_StyleAttr_Coleccion_enum",
		"QST_StyleAttr_RoutingCost_double",
		"QST_StyleAttr_PNPImportadoCIF_double",
		"QST_StyleAttr_PNPNacionalCIF_double",
		"QST_StyleAttr_ManufacturadoCIF_double",
		"QST_styleAttr_costototal_double",
		"QST_styleAttr_Precioventa_double",
		"QST_Style_ComiteComent_string",
		ActualSizeRange,
		DefaultStyleType,
		DefaultSize,
		"_ExportedDate_"
	FROM "DESCARGA_PLM".dbo.Style
	where ParentSeason<>'centric';

STORE Product_PLM INTO [..\QVD\PLM\Product_PLM.QVD](qvd);
DROP TABLE Product_PLM;
