/*----------------------------------------------------------------------------------------------------
	Detalle :
	Extracción de Dimensiones: Extracción de Maestro de Tallas de los Productos
	-------------------------------------------------------------------------------------------------
	Fecha       |   Desarrollador   |   Modificación
	-------------------------------------------------------------------------------------------------
	11/03/2016  |   malemos         |   Inicio de Configuración
*****************************************************************************************************/
ProductoTalla_QV:
	SQL Select
		//CodigoProducto,
		EstadoSincronizacion,
		FechaActualizacion,
		FechaCreacion,
		IdPLM,
		Talla
	From ProductoTalla_QV;

STORE ProductoTalla_QV INTO [..\QVD\PLM\ProductoTalla_QV.QVD](qvd);
DROP TABLE ProductoTalla_QV;