/*----------------------------------------------------------------------------------------------------
	 Detalle :
		Extracción de Dimensiones: Style Material BOM
	-------------------------------------------------------------------------------------------------
	Fecha       |   Desarrollador   |   Modificación
	-------------------------------------------------------------------------------------------------
	10/18/2016  |   malemos         |   Inicio de Configuración
*****************************************************************************************************/
StyleMaterialBOM:
SQL SELECT
	"_id_",
	"Node Name",
	"Node Name2",
	"__Parent__",
	"_ExportedDate_"
FROM "DESCARGA_PLM".dbo.StyleMaterial;

STORE StyleMaterialBOM INTO [..\QVD\PLM\StyleMaterialBOM.QVD](qvd);
DROP TABLE StyleMaterialBOM;
