/*----------------------------------------------------------------------------------------------------
	 Detalle :
		Extracción de Dimensiones: Style Material BOM Refs
	-------------------------------------------------------------------------------------------------
	Fecha       |   Desarrollador   |   Modificación
	-------------------------------------------------------------------------------------------------
	10/18/2016  |   malemos         |   Inicio de Configuración
*****************************************************************************************************/

StyleMaterialBOMRefs:
SQL SELECT
	fromID,
	toID,
	attrName,
	mapkey
FROM "DESCARGA_PLM".dbo."StyleMaterial_refs";

STORE StyleMaterialBOMRefs INTO [..\QVD\PLM\StyleMaterialBOMRefs.QVD](qvd);
DROP TABLE StyleMaterialBOMRefs;
