/*----------------------------------------------------------------------------------------------------
 Detalle :
    Extracción de Dimensiones: Detalle  de codigos
-------------------------------------------------------------------------------------------------
Fecha       |   Desarrollador   |   Modificación
-------------------------------------------------------------------------------------------------
10/18/2016  |   malemos         |   Inicio de Configuración
*****************************************************************************************************/
Enums_PLM:
SQL SELECT 
	"_id_",
	"Node Name",
	Description,
	Custom,
	DependsOn,
	Description2,
	"Node Name2",
	Internal,
	"_DisplayName_",
	"_ExportedDate_"
FROM "DESCARGA_PLM".dbo.Enums;

STORE Enums_PLM INTO [..\QVD\PLM\Enums_PLM.QVD](qvd);

DROP TABLE Enums_PLM;