/*----------------------------------------------------------------------------------------------------
 Detalle :
    Extracción de Dimensiones: FotosStyle
-------------------------------------------------------------------------------------------------
Fecha       |   Desarrollador   |   Modificación
-------------------------------------------------------------------------------------------------
09/22/2016  |   malemos         |   Inicio de Configuración
02/02/2017  |   Alejandro Saa G |   Cambio del nombre de la tabla y de los atributos
*****************************************************************************************************/
FotosStyle:
SQL SELECT
	CodigoProducto,
	RutaProducto
FROM "FotosSyle";

STORE FotosStyle INTO [..\QVD\PLM\FotosStyle.QVD](qvd);
DROP TABLE FotosStyle;
