/*----------------------------------------------------------------------------------------------------
 Detalle :
    Extracción de Dimensiones: Productos PLM
-------------------------------------------------------------------------------------------------
Fecha       |   Desarrollador   |   Modificación
-------------------------------------------------------------------------------------------------
10/18/2016  |   malemos         |   Inicio de Configuración
*****************************************************************************************************/

ProductRefs:
SQL SELECT
	fromID,
	toID,
	attrName,
	mapkey
FROM "DESCARGA_PLM".dbo."Style_refs";

STORE ProductRefs INTO [..\QVD\PLM\ProductRefs.QVD](qvd);
DROP TABLE ProductRefs;
